# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded Ffidlx 0.7 [list source [file join $dir snodbc-b84expanded.tcl]]
package ifneeded odbc::ffi 1.1 [list source [file join $dir snodbc-b84expanded.tcl]]
package ifneeded odbc::obj 1.2 [list source [file join $dir snodbc-b84expanded.tcl]]
package ifneeded odbc::wrap 1.1 [list source [file join $dir snodbc-b84expanded.tcl]]
package ifneeded reftrace 1.0 [list source [file join $dir snodbc-b84expanded.tcl]]
package ifneeded snodbc 1.2.20080522 [list source [file join $dir snodbc-b84expanded.tcl]]
